### ISSUE TITLE
Colorize SVG files

### ISSUE THREAD

**Issue by bitjson** [KamiKillertO/vscode-colorize#10]
Thanks for the great extension!

It would be great if this plugin also colorized SVG files, e.g.: https://raw.githubusercontent.com/bitpay/copay/master/app-template/copay/img/logo-negative.svg

There is a `#FFFFFF` which is somewhat hard to spot without colorization.

**Comment by KamiKillertO** [comment]
Thanks 😃 

I've to admit that `#ffffff` is very hard to find.
I'd planned to release a new version today (or tomorrow) with stylus support, I'll add svg too.

**Comment by KamiKillertO** [comment]
v0.3.2 is out.
Colors inside SVG are now colored (rgb(a) and hexa)
