### ISSUE TITLE
Wont colorize 2nd colour in gradient statement (Sass)

### ISSUE THREAD

**Issue by YuziRussianHax** [KamiKillertO/vscode-colorize#11]
![image](https://cloud.githubusercontent.com/assets/14042959/23665256/a52cdfe8-0360-11e7-81cc-2d3655ecbeb1.png)
As you see there is no color highlighting for second color argument in gradient style statement. (Sass)
P. S. Sorry for my english.

Ubuntu 16.10, VSCode 1.10.1

**Comment by KamiKillertO** [comment]
Done 👍 
The fix will be ship in the next release
