### ISSUE TITLE
SCSS variable highlight not working properly

### ISSUE THREAD

**Issue by mignz** [KamiKillertO/vscode-colorize#111]
I'm getting this:

![screen shot 2018-01-22 at 15 30 54](https://user-images.githubusercontent.com/358114/35231831-5600eec0-ff89-11e7-8d35-c6eecfa8bf68.png)

The white bar after { is not the cursor, it's something to do with colorize. Same after ;.

Let me know if I can help.

**Comment by KamiKillertO** [comment]
Yeah it happens sometimes. Closing/reopening the file should fix this. 
I'm currently refactoring the variables support to fix this kind of things.

**Comment by daraclare** [comment]
The SCSS variables are not working for me at all, I'm on VSCode version 1.26.1

**Comment by KamiKillertO** [comment]
Yeah it's because sass variables are not colorized by default. You can enable sass variables support by updating the config `colorize.colorized_variables` like this `["CSS", "SASS"]`

**Comment by daraclare** [comment]
Thanks for the quick response. It is now working for some scss variables, but not the darkened or lightened ones:

<img width="309" alt="screen shot 2018-08-17 at 12 51 28" src="https://user-images.githubusercontent.com/5235711/44264947-6578ce00-a21c-11e8-8b4b-a759f9ab88ca.png">

**Comment by KamiKillertO** [comment]
I don't support lighten, darken... Yet ><. But it should be supported in the next release 🤞

**Comment by daraclare** [comment]
Ah, ok, thanks for your help, and your extension :)
