### ISSUE TITLE
Color in blocks

### ISSUE THREAD

**Issue by robsonsobral** [KamiKillertO/vscode-colorize#112]
Hi! Thank you for the extension.

Is it possible to show the color in blocks at right of the color code, instead of background? Isnt always easy to read the color values.

Thank you!

**Comment by KamiKillertO** [comment]
HI,

It's not planned yet.
Did you have any hard readable color values examples? I'll see if I can improve readability

**Comment by ekfuhrmann** [comment]
Looks to me like your luminance check needs to just be slightly tweaked.  Here are a few examples with contrast issues.

![image](https://user-images.githubusercontent.com/8878152/35444029-27dc306e-027b-11e8-9e71-7c3695a8b8dd.png)

Specifically `#F8D426`, `#9DE0BF`, `#B0B0FF`, `#F4CCE0`, and `#ACB5BE` are all quite difficult to read.

I'm not sure how you are handling your luminance check, but this is what I've used on another project with some success:

```js
        const rgb = parseInt(hexColor, 16); // convert rrggbb to integer
        const r = (rgb >> 16) & 0xff; // extract red
        const g = (rgb >> 8) & 0xff; // extract green
        const b = (rgb >> 0) & 0xff; // extract blue

        const luma = 0.2126 * r + 0.7152 * g + 0.0722 * b; // per ITU-R BT.709

        if (luma > 150) {
            // action
        }
```

The above snippet does account for the color issues I previously mentioned in case you go with something like this.

Hope this helps!

**Comment by robsonsobral** [comment]
I don't have an example right now, @KamiKillertO . I asked mostly because of my experience with similar issues with Sublime Text Color Highlighter. I'm sorry.

**Comment by KamiKillertO** [comment]
Thanks @ekfuhrmann for those exemples. I'll update the luminance check to fix this issue

**Comment by KamiKillertO** [comment]
I've made a few research on luminance and contrast and I think I will follow the WCAG specs here https://www.w3.org/WAI/WCAG20/quickref/#visual-audio-contrast-contrast. That fix all contrast issues 😄

**Comment by ekfuhrmann** [comment]
Awesome, thanks for the great work on this plugin!

**Comment by KamiKillertO** [comment]
I've just released the new version with the fix, everything should be fine now.

**Comment by ekfuhrmann** [comment]
Looks good on my end. Thanks again for the quick turnaround!

**Comment by KamiKillertO** [comment]
It's not working with variables 😢 

<img width="348" alt="screen shot 2018-01-31 at 16 05 11" src="https://user-images.githubusercontent.com/9579729/35630065-9d8d1b92-06a0-11e8-9286-2cff91199e7f.png">

**Comment by robsonsobral** [comment]
Thank you so much, @ekfuhrmann !

And thanks for the effort, @KamiKillertO .

**Comment by missmatsuko** [comment]
Is it now possible to show only the swatch next to the colour and not in addition to the background colour? I just prefer that style. I like how Pigments for Atoms has a variety of styles to choose from: https://github.com/abe33/atom-pigments#marker-type

**Comment by KamiKillertO** [comment]
@missmatsuko there's no such option yet, I will add it in the future. But for the time being I'm focusing on other topics. However if you have times and you don't want to wait, I suggest you to make a PR ^^. You should find everything you need [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.createTextEditorDecorationType) and [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions)
