### ISSUE TITLE
SCSS variables ending in dash-number / underscore_something don't show preview

### ISSUE THREAD

**Issue by ronalson** [KamiKillertO/vscode-colorize#113]
I'm getting a weird behavior whenever my variables are named with a `-` (dash) followed by a number or a `_` (underscore) followed by a number or letter.

This is the output I'm getting:

![variable-issue](https://user-images.githubusercontent.com/8891651/35462252-4f2e23f0-02d2-11e8-8f9a-004522cc9d61.png)

Code from print:

```scss
$normal-var:   #CC3332;
$with-number1:  #209bEE;
$with-letterA:  #95C93f;
$with-dash-1:  #E0B125;
$with-dash-A:  #B76BFF;
$with-underscore_B:  #FF470F;
$with-underscore_2:  #00B9B5;

$colorA: $normal-var;
$colorB: $with-number1;
$colorC: $with-letterA;
$colorD: $with-dash-1;
$colorE: $with-dash-A;
$colorF: $with-underscore_2;
$colorG: $with-underscore_B;
```

---

VSCode version: 1.19.3
Colorize: v0.6.11

**Comment by KamiKillertO** [comment]
🤔 it seems that the RegExp used for variables extractions does not accept those variables name 😥. I will fix it as soon as possible. Thanks for the feedback

**Comment by ronalson** [comment]
Wow. That was fast! Thanks for the attention and for maintaining this awesome extension. 💯 Looking forward for the updated.

**Comment by KamiKillertO** [comment]
I've juste released the new version ^^. Let me know if you still have issues
