### ISSUE TITLE
Add support for HTML Color Names

### ISSUE THREAD

**Issue by KamiKillertO** [KamiKillertO/vscode-colorize#12]
Colorize should generate decorations for these colors : [https://www.w3schools.com/colors/colors_names.asp](https://www.w3schools.com/colors/colors_names.asp)

**Comment by alexmironof** [comment]
It will be nice if it wont colorize names wich goes before colon like `$mid-gray-blue-button: #595f79`.
I've removed `Color Highlight` plugin and use `Colorize` because of this weird behavior...
