### ISSUE TITLE
working erratically with javascript 

### ISSUE THREAD

**Issue by Yimiprod** [KamiKillertO/vscode-colorize#127]
As in this screenshot, it colorize only the variable name and not the values.
<img width="330" alt="colorize error" src="https://user-images.githubusercontent.com/2227867/37784577-701ebc04-2df8-11e8-9cf9-9313e979ac85.png">

**Comment by KamiKillertO** [comment]
indeed 🤔. I'll fix it as soon as possible. Thanks for the feedback 👍

**Comment by KamiKillertO** [comment]
Fixed 👍. 
<img width="406" alt="screen shot 2018-03-23 at 09 32 18" src="https://user-images.githubusercontent.com/9579729/37819282-37326a82-2e7d-11e8-9343-78328a0001aa.png">

I'll soon release a new version with the fix 😄

**Comment by KamiKillertO** [comment]
I've just publish a new version with a fix for your problem.
