### ISSUE TITLE
Color Rendering Issues

### ISSUE THREAD

**Issue by pingshunhuangalex** [KamiKillertO/vscode-colorize#129]
Just migrate from Atom, and finally found something that does things similar to Atom `pigment`. Please keep up the good work.

I noticed 2 issues when poking around the extension:
1. variables used in `rgba` is not taking the opacity into account. Instead of highlighting just the variable, `rgba` part should have a higher priority
2. when highlighting color displayed in `rgb` or `rgba`, the `space character` is also highlighted, which should not be the case

The above 2 issues can be shown in the screenshot below. Thanks.
![capture](https://user-images.githubusercontent.com/17170199/37874550-b7d5b4e0-307c-11e8-86a0-c84a317eefba.PNG)

**Comment by KamiKillertO** [comment]
Thanks for the feedback. For the first issue there's already #75. I'm not sure to understand thé second issue

**Comment by pingshunhuangalex** [comment]
Thanks for reply @KamiKillertO 

The second issue is about space rendering. Note that I turned on `space rendering` which display the `space` as a dot. According to the GIFs in readme, you actually did the same.

Normally, the dot is in a color that is really close to the background so it won't attract that much attention. However, when it's highlighted by `colorize`, it's forced to use the same contrast color as the coding text which you can see from the second line of the screenshot above.

What I'm suggesting is the dot should still be a color close to the background, i.e. the color used by `colorize`. If this is too much effort, then at least we should keep it as it is instead of making it also use the contrast color.

Hope I explained the issue clearer this time. Thanks.

**Comment by KamiKillertO** [comment]
Ok I see now 😄.
I'll think about. Bye the way how `pigment` handle thus behavior?

**Comment by KamiKillertO** [comment]
Well it's not that simple in vscode 🙄. We don't have access to `HTML` or `CSS` 😞.
