### ISSUE TITLE
hex highlight 0xffffff

### ISSUE THREAD

**Issue by djmisterjon** [KamiKillertO/vscode-colorize#132]
hi, thank work fine.
 its possible to add a missing feature for detect code like **0x**ffffff ???
```javascript
  var lineX_ = new PIXI.Graphics();
      lineX_.lineStyle(48, 0xF46036);
```

thank a lot

**Comment by KamiKillertO** [comment]
Sure no problem 👍

**Comment by KamiKillertO** [comment]
I've just publish a new version with a fix for your problem
