### ISSUE TITLE
variable highlighting stopped working in the latest insider version

### ISSUE THREAD

**Issue by pingshunhuangalex** [KamiKillertO/vscode-colorize#134]
It seems like the beta variable highlighting has stopped working after I upgraded to `1.22` this morning.

**Comment by KamiKillertO** [comment]
It's not related to vscode `1.22`. I've release a new version yesterday with a small error inside ><.
But I've just publish a patch and everything should work perfectly now

**Comment by pingshunhuangalex** [comment]
Confirmed, things are back to harmony now~
