### ISSUE TITLE
Color highlighter bug

### ISSUE THREAD

**Issue by Mleur** [KamiKillertO/vscode-colorize#135]
Hi! Recently for no apparent reason all the colors began to appear like this:
![color](https://user-images.githubusercontent.com/32208651/38564659-4553a5f8-3ce8-11e8-9330-c4e52e4077ef.png)

(Settings: "ha_style": "filled")

Maybe You know how to fix color highlighter?

**Comment by KamiKillertO** [comment]
🤣 Sorry but I've no idea about how to fix color highlighter. I can only suggest you to use colorize ^^

**Comment by Mleur** [comment]
Ups, Sorry :)
