### ISSUE TITLE
Colorizing of SCSS variables seems to be broken

### ISSUE THREAD

**Issue by chipcullen** [KamiKillertO/vscode-colorize#146]
Thank you for this great extension!

I'm not sure if I'm missing something or not, but I currently can't seem to get colorization to work on color variables in an SCSS file. For example:

![screen shot 2018-05-03 at 10 03 19 am](https://user-images.githubusercontent.com/60903/39581425-8b49b178-4eb9-11e8-8b31-a7a75eac177f.png)

Note how the hex values colorize as expected, but none of the variables do - such as `$orange`.

This is also true for imported color variables.

Here are my colorize user settings:

```
"colorize.languages": [
    "javascript",
    "css",
    "sass",
    "scss",
    "less",
    "pcss",
    "sss",
    "stylus",
    "xml",
    "svg"
  ],
  "colorize.hide_current_line_decorations": false,
```

I've also temporarily disabled all other extensions, restarted VS code, and closed / reopened the file. Nothing seems to be working. I am on VS Code version 1.22.2 / Mac OS 10.12.6.

If there is any other information that I can furnish, or if there is some kind of configuration that I have missed, please let me know. Thank you!

**Comment by KamiKillertO** [comment]
Hi, sorry for the late answer. Do you have enable variables support? 
https://github.com/KamiKillertO/vscode-colorize#colorizeactivate_variables_support_beta-boolean-default-false

**Comment by chipcullen** [comment]
Aw jeeze - I'm so sorry. I totally missed that setting in the readme. 🤦‍♂️ 

It's working now. I've spotted one bug, but it's a different issue. I'll close this and open a different one.

**Comment by crutchcorn** [comment]
The README link seems to be broken for this @KamiKillertO
