### ISSUE TITLE
Highlighting incorrect on custom properties

### ISSUE THREAD

**Issue by evanwarner** [KamiKillertO/vscode-colorize#152]
I understand that variable support is still a WIP, but wanted to put this here as an active bug. Highlighting of custom property colors was working pretty well for a while, but sometime recently the highlighting got offset incorrectly:

![colorize-highlight](https://user-images.githubusercontent.com/6453842/41493212-db81dd74-70b9-11e8-80a8-3ee4fd4e5cec.png)

It's always offset early by 4 characters, capturing the `var(` instead of the full text within the parenthesis.

**Comment by KamiKillertO** [comment]
Indeed, I'll fix it as soon as possible. Thanks for reporting 😄

**Comment by KamiKillertO** [comment]
I've just release the fix. Sorry for the disturbance.

**Comment by evanwarner** [comment]
Looks good, thanks!
