### ISSUE TITLE
Check for Colors in JS files

### ISSUE THREAD

**Issue by deadcoder0904** [KamiKillertO/vscode-colorize#159]
I know this supports all CSS files but wouldn't it be great if it supports all kinds of files.

I am a color noob & don't understand which color it is when I type the hex color code & to make an application look visually pleasing I change colors all the time & it gets boring when I switch applications so I think as this is a great extension why not support every file rather than just CSS files. 

Idk how a VSCode Extension API works so don't know the complexity but it will help for lots of React developers who use Styled Components / Emotion or any CSS in JS library.

```js
import styled from "emotion";

const Logo = styled.img`
  width: 5rem;
  height: 5rem;
  color: #bada55;
`;
```

Currently my file looks like this & would love to have color highlighted in this extension.

**Comment by KamiKillertO** [comment]
Hi,

There's a two config options which allows you to enable colorize for other type of files than CSS. The first is [`languages`](https://github.com/KamiKillertO/vscode-colorize/blob/develop/README.md#colorizelanguages-array) and the second is [`files_extensions`](https://github.com/KamiKillertO/vscode-colorize/blob/develop/README.md#colorizefiles_extensions-array)

**Comment by deadcoder0904** [comment]
Ohh Jesus didn't knew that. Thank you so much 😍
I'll try & reopen if it doesn't work :)

**Comment by deadcoder0904** [comment]
Wow it works had to set languages to `javascript` & `javascriptreact`. Thank you :)
