### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by borispov** [KamiKillertO/vscode-colorize#160]
Hello, 
For some reason, the extension works for .css & .scss but doesn't work for my .sass files, 
what could that be? 
In the settings, I've checked and sass is not removed out of the supported langs..

**Comment by borispov** [comment]
I've actually added .sass in the file extensions and it worked,
sorry for bothering.

**Comment by rikusen0335** [comment]
A useful tip:
You can set it like this if you use SASS (SCSS)
```
    "colorize.colorized_variables": [
      "SASS"
    ]
```
https://github.com/KamiKillertO/vscode-colorize#colorizecolorized_variables

Don't forget `,` on previous line :)
