### ISSUE TITLE
dot values

### ISSUE THREAD

**Issue by VBagmut** [KamiKillertO/vscode-colorize#164]
Add support for dot values. For example `hsla(270.54, 29.82%, 45.83%, 1)`

With something like that `/((rgb|hsl)?a?\([\d]{1,3}?\.?[\d]{1,}%?,\s*[\d]{1,3}?\.?[\d]{1,}%?,\s*[\d]{1,3}?\.?[\d]{1,}%?(,\s*\d?\.?\d+)?\))/gi`

**Comment by KamiKillertO** [comment]
I'm currently working on it.
I've never written hsl or rgb colors with dot values, is it something common for you?

**Comment by KamiKillertO** [comment]
I've just release a new version which highlight rgb(a) and hsl(a) colors with decimal values.
