### ISSUE TITLE
 Incredibly high CPU and RAM usage. 

### ISSUE THREAD

**Issue by jcklpe** [KamiKillertO/vscode-colorize#166]
I have quite a few extensions for my VScode work environment but after installing this extension it alone made my cpu usage jump from 30% to 100% just while idling. Is there a memory leak in this perhaps? What's particularly strange is that I have other color hilighting type extensions installed and this is the only one which is causing this issue. 

I rather prefer this extensions presentation of the color information. I have the other ones installed just because they allow for easy stuff like color picking or conversion between hex and RGB. This one seems from the outside to be simplest and yet it seems to be having the most resource needs?

I have a surface book 2 so it's a pretty hefty machine for a laptop. Seems weird that a single color extension could basically max out it's resources....?

**Comment by thedonquixotic** [comment]
Yes only with vscode when the plugin is enabled. I went through and turned off each plugin one at a time and the difference between this and without was huge. I turned it off and restarted vscode several times to check and this is def the biggest single drain on the CPU and stuff. 

I would say that I work on medium sized projects. Wordpress themes is all really.

**Comment by ctf0** [comment]
same here

**Comment by KamiKillertO** [comment]
Ok I think I know what's the problem. When you open vscode my extension start by looking all files in you project, then open all files that might contain CSS/SASS/LESS... and parse the file content. So maybe in your case too much files are opened and parsed. I'll do my best to improve this part 😀

**Comment by thedonquixotic** [comment]
Thanks! Keep up the great work :)

**Comment by KamiKillertO** [comment]
Hi,

I'm working on something that might solve your problem. I'll add a settings that permit you to include/exclude files from the variables search 😄

**Comment by Arkkimaagi** [comment]
We have a huge project, lots of files, but only one that should be scanned for color variables. This approach sounds promising, please allow limiting the scanning to a folder or file and then let variables be colored in all same files or content of same type.

**Comment by KamiKillertO** [comment]
Hi @jcklpe, sorry for the delay, I've been working hard on this issue. I think I finally came up with a good solution, everything is explained in details here https://github.com/KamiKillertO/vscode-colorize/pull/170
