### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by AndreyKonogray** [KamiKillertO/vscode-colorize#179]
After installation of colorize or all autocomplate, it takes some time and the program hangs, after which the emmet, autocomplete and some other plugins stop working. The problem appears after the finishing of scanning files (on the status bar at the bottom of the workstation)

**Comment by KamiKillertO** [comment]
@AndreyKonogray it seems that you're encountering the same problem that the #174 .
I suggest you to modify your colorize settings to target the files that need to be colorized

**Comment by AndreyKonogray** [comment]
And where can I do this?)

**Comment by KamiKillertO** [comment]
You should open the vscode settings pages https://code.visualstudio.com/docs/getstarted/settings
Then update the settings [`colorize.languages`](https://github.com/KamiKillertO/vscode-colorize#colorizelanguages-array), [`colorize.include`](https://github.com/KamiKillertO/vscode-colorize#colorizeinclude) and [`colorize.exclude`](https://github.com/KamiKillertO/vscode-colorize#colorizeeclude).
There's a good exemple of setting in this [comment](https://github.com/KamiKillertO/vscode-colorize/issues/174#issuecomment-439403843)

**Comment by AndreyKonogray** [comment]
Thank. And it really helped. And you can include colorize in html. I wrote in the settings, but nothing works.

**Comment by KamiKillertO** [comment]
did you add `"html"` in the setting `colorize.languages`

**Comment by AndreyKonogray** [comment]
Yes

**Comment by KamiKillertO** [comment]
Did you have an exemple of html to share ?

**Comment by AndreyKonogray** [comment]
<meta name="theme-color" content="#ff6408">

**Comment by KamiKillertO** [comment]
🤔 stupid question but is your cursor ont this line ?

**Comment by AndreyKonogray** [comment]
I do not understand your question. I would like the color to be the backround in html. There is a possibility?)
