### ISSUE TITLE
Also copy the highlight colors with the HTML when coping the file contents

### ISSUE THREAD

**Issue by evandrocoan** [KamiKillertO/vscode-colorize#180]
For example, if I have the following: 
![image](https://user-images.githubusercontent.com/5332158/49172966-87104800-f329-11e8-9030-b280a0c70407.png)

And I select all text and copy paste it on Microsoft Word, it would also copy the highlighting backgrounds. But currently only the syntax coloring is copied:
![image](https://user-images.githubusercontent.com/5332158/49173050-c2127b80-f329-11e8-84e1-dee31fee64b4.png)

**Comment by KamiKillertO** [comment]
Hi,

I'm not sure I can do such a thing. Colorizations are generated using vscode API, those API should deal with copy/paste. I suggest you to open a vscode's issue/feature-request
