### ISSUE TITLE
Issues with IntellSense

### ISSUE THREAD

**Issue by aprather51** [KamiKillertO/vscode-colorize#185]
For month I had issues with VSCode intelliSense for JavaScript (after upgraded to 1.29). I consulted with VSCode support and was advised to disenage all extensions that I have installed to diagnose for problems. After disenage extensions, the intelliSense worked again. Then I enable each extensions one by one and until whenever extension is causing intelliSense to cease from working,  Colorize is the one that cause intelliSense to stuck at Load only when I work with JavaScript. I have no issues with SCSS, CSS. 

![intellisense](https://user-images.githubusercontent.com/10257247/50603203-5919a880-0e7f-11e9-882b-fbf3e364f0d1.jpg)

**Comment by KamiKillertO** [comment]
🤔 that's strange my extension doesn't deal with intelliSense at all. Does this problem appears soon after opening vscode? Did you have `javascript` in one of your settings for `colorize` ?

**Comment by aprather51** [comment]
No, the problem appears after launching intelliSense few times... See if you could hit ctrl + backspace few times until it get stuck at loading... 

My user setting saved with vscode.json...
```
  "colorize.languages": [
        "javascript",
        "css",
        "sass",
        "scss",
        "svg"
    ],
```

**Comment by KamiKillertO** [comment]
I cannot reproduce the problem, I'll keep an eye on this problem but I cannot guarantee that i'll solve it soon

**Comment by aprather51** [comment]
Thank you for your time, I will go ahead and close it.  Please acknowledge whenever problem is solved.
