### ISSUE TITLE
Feature request: show "Found variables" only for style files.

### ISSUE THREAD

**Issue by mohsenkhanpour** [KamiKillertO/vscode-colorize#198]
Hey thanks for this great extension. 
I have seen VS Code extensions that show something in status bar when a particular type of files is being edited.
Colorize shows `Found variables` in status bar at all times.

I am talking about this : 
https://github.com/KamiKillertO/vscode-colorize/blob/ef74c7c75c7d2e8d0a4d23d6841db48fcbdd25a1/src/lib/variables/variables-manager.ts#L32

We should make `statusBar.text` only visible in file types included in `colorize.include`.
I believe this makes the extension less intrusive and more enjoyable to work with.

**Comment by KamiKillertO** [comment]
Maybe, I'll look into it 👍
