### ISSUE TITLE
Not working when on split view

### ISSUE THREAD

**Issue by dukearena** [KamiKillertO/vscode-colorize#20]
**Issue Type**: bug
**OS**: windows 10
**vscode version**: 1.10.2

**Issue Description**:
1. Open any file (I used a typescript file), create some color variable that works with colorize.
2. Move the file to right or left of another file, to create a split view
3. The variables are no more colored

This is an example, sorry for the low quality
![colorize_split_screen_bug](https://cloud.githubusercontent.com/assets/11449047/23905592/d579d352-08cb-11e7-841a-4f13972a0b99.gif)

**Comment by KamiKillertO** [comment]
Thanks for the feedback 👍.
I'll do my best to fix it for the next release 😸.

**Comment by dukearena** [comment]
Tested on version 0.4.0 - everything works fine.
Well done 👍
