### ISSUE TITLE
colorize only foreground

### ISSUE THREAD

**Issue by gregcousin126** [KamiKillertO/vscode-colorize#216]
Hi there, I am just wondering if it is possible to only colorize the foreground of the tag names. so just the text and not the background.

**Comment by KamiKillertO** [comment]
Hello,
Yes it's totally possible. I can add a setting option to do so 👍

**Comment by gregcousin126** [comment]
Perfect! that would be great if you could. the plugin is very useful!

**Comment by gregcousin126** [comment]
do you know when you might have it as a downloadable on the vscode plugin platform?

**Comment by KamiKillertO** [comment]
I've run some tests and I don't know if I will add this feature. The idea of colorize is to make colors more visible in files and this feature does not make colors more visibles.
<img width="209" alt="Screenshot 2019-03-26 at 21 36 56" src="https://user-images.githubusercontent.com/9579729/55032027-4f33bb80-5010-11e9-9969-d191c98eb170.png">

**Comment by gregcousin126** [comment]
oh ok, that makes sense. would you mind by chance maybe  sending me this feature? and i can customize it? if you already have it working?

**Comment by gregcousin126** [comment]
Would that be ok?

**Comment by gregcousin126** [comment]
Hi,

Just following up to see if it's ok that i can have the ability to simply have the hex string foreground colorized rather than the background since you tested the plugin. Would this be  ok with you?

Best,
GC
