### ISSUE TITLE
Variable color support

### ISSUE THREAD

**Issue by IIIu6ko** [KamiKillertO/vscode-colorize#22]
Please implement color support in variables.
![5e04c0c45c194e92a1c8f8471b728762](https://cloud.githubusercontent.com/assets/20703084/24326509/99242954-11c0-11e7-8c2b-4f89325c88a6.png)

Pigments for atom has such a functional
https://atom.io/packages/pigments

**Comment by daviddarke** [comment]
+1

**Comment by KamiKillertO** [comment]
It's planned but not yet 😞 . I'll first add support for hsl colors

**Comment by IIIu6ko** [comment]
Do not forget to add cssnext variables:
```
:root {
  --mainColor: red;
}

a {
  color: var(--mainColor);
}
```

http://cssnext.io/features/#custom-properties-var

**Comment by KamiKillertO** [comment]
I've release a new version `0.6.0` with variables supports in beta.

**Comment by evanwarner** [comment]
Yes! Seems to be working pretty well. I'll open a separate issue for the one thing I've noticed so far.
