### ISSUE TITLE
Incorrect color in XML Color Using ARGB

### ISSUE THREAD

**Issue by twowei** [KamiKillertO/vscode-colorize#226]
Color Hex in Figma
![image](https://user-images.githubusercontent.com/11190955/55705223-e5a0ad80-5a10-11e9-9136-ea5c1e84d07a.png)

And in VSC
![image](https://user-images.githubusercontent.com/11190955/55705268-00732200-5a11-11e9-95c1-08d9ec0c956f.png)

http://devdeeds.com/color-opacity-using-xml-in-android/

**Comment by KamiKillertO** [comment]
I've never heard of ARGB before ><. I can easily support ARGB colors by adding a new color type 👍 but it will not be enable by default to avoid conflict with the HEX colors. You will have to enable it in this [setting](https://github.com/KamiKillertO/vscode-colorize#colorizecolorized_colors-array)

**Comment by KamiKillertO** [comment]
I've release a new version with this feature. After updating you will be able to activate ARGB colorization by updating your colorize's setting, just replace `HEXA` with `ARGB` in the setting [`colorize.colorized_colors`](https://github.com/KamiKillertO/vscode-colorize#colorizecolorized_colors-array)
