### ISSUE TITLE
Not working in JS (astroturf)

### ISSUE THREAD

**Issue by ivancuric** [KamiKillertO/vscode-colorize#233]
![image](https://user-images.githubusercontent.com/2827047/56027756-f6099e80-5d16-11e9-8ed5-eab7d70d85cb.png)

I've tried adding `javascriptreact` to the languages list without success:
```json
  "colorize.include": [".tsx", ".jsx", ".ts", ".js"],
  "colorize.languages":[
    "css",
    "sass",
    "scss",
    "less",
    "postcss",
    "sss",
    "stylus",
    "xml",
    "svg",
	"javascript",
    "javascriptreact"
  ],
```

**Comment by KamiKillertO** [comment]
Thanks for reporting I will have a look

**Comment by KamiKillertO** [comment]
Is this file located in the current workspace ?

**Comment by ivancuric** [comment]
Yep.

**Comment by KamiKillertO** [comment]
Ok 🤔 does the colorization works on other files ? Like css files ?

**Comment by ranihorev** [comment]
Same for me. It works with css files but not with tsx.
Thanks!

**Comment by KamiKillertO** [comment]
I'm sorry but I haven't been able to reproduce yours issues @ranihorev @ivancuric .
Have you try adding `typescriptreact` in the setting `colorize.languages`

![Jun-01-2019 16-16-15](https://user-images.githubusercontent.com/9579729/58749647-c3636300-8488-11e9-81fa-1fc491db62d3.gif)

You can also use `colorize.include`

![Jun-01-2019 16-19-05](https://user-images.githubusercontent.com/9579729/58749664-058ca480-8489-11e9-94a3-6c3faf6e1e64.gif)

**Comment by sethstha** [comment]
```
    "colorize.languages": [
        "css",
        "scss",
        "javascriptreact",
        "typescriptreact"
    ],
```

Remove the react and it works
```
    "colorize.languages": [
        "css",
        "scss",
        "javascript",
        "typescript"
    ],
```

**Comment by jcayzac** [comment]
It doesn't work in template strings:

```js
const work = [
  '#ffaa00',
  "#ffaa00",
];

const doesntWork = [
  `#ffaa00`,
];
```

**Comment by KamiKillertO** [comment]
@jcayzac sorry for the delay. I've published a new version that add support for template strings
