### ISSUE TITLE
Coloring variables across JS files

### ISSUE THREAD

**Issue by jasonscholefield** [KamiKillertO/vscode-colorize#234]
![Screen Shot 2019-04-15 at 11 55 53 AM](https://user-images.githubusercontent.com/10052961/56157950-9bba4900-5f75-11e9-91ef-b975e7240458.png)

So app-theme houses all my color definitions. Any way I can get it to display on theme.colors.black here?

**Comment by KamiKillertO** [comment]
Unfortunately no. There's no support for CSS in JS yet
