### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hasanshaker** [KamiKillertO/vscode-colorize#242]
- Issue Type: `Performance`
- Extension Name: `vscode-colorize`
- Extension Version: `0.8.10`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Shaker\kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KamiKillertO** [comment]
Can you share the file ?
