### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by elefank** [KamiKillertO/vscode-colorize#247]
- Issue Type: `Performance`
- Extension Name: `vscode-colorize`
- Extension Version: `0.8.10`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/hernan/kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by KamiKillertO** [comment]
Can you share the file?

**Comment by KamiKillertO** [comment]
@elefank ?
