### ISSUE TITLE
is colorize compatible with dart files? Flutter Code on Vscode

### ISSUE THREAD

**Issue by divineforge** [KamiKillertO/vscode-colorize#264]
Hi I configured accordingly in the vscode user setting json. 
to enable the detection of dart files, with *.dart extension, such that hoping this would higlight the codes like

```
const Color ColorCustomStepsBG = Color(0XFFCCCCCC);
const Color warningRed = Color(0xFFA10C0C);
```

with following configuration

```javascript
   "colorize.languages": [
        "css",
        "sass",
        "scss",
        "less",
        "postcss",
        "sss",
        "stylus",
        "xml",
        "svg",
        "dart"
    ],
    "colorize.colorized_colors": [
        "BROWSERS_COLORS",
        "HEXA",
        "RGB",
        "HSL"
    ],
```

it doesn't work for me though. Is there something wrong with the configuration or should this be considered as an enhancement?

**Comment by KamiKillertO** [comment]
It should work indeed.
It seems that the extraction of hexa colors starting with `0x` was not working. I've made a patch and release a new version, it should be working now
