### ISSUE TITLE
Display with border instead of background

### ISSUE THREAD

**Issue by shungo27** [KamiKillertO/vscode-colorize#274]
.vscode/extensions/kamikillerto.vscode-colorize-0.8.11/out/src/lib/colors/color-decoration.js

```
    _generateDecorator() {
        let backgroundDecorationType = vscode_1.window.createTextEditorDecorationType({
            // borderWidth: '1px',
            borderWidth: '0 0 1px 0',
            borderStyle: 'solid',
            borderColor: this.color.toRgbString(),
            // backgroundColor: this.color.toRgbString(),
            // color: color_util_1.generateOptimalTextColor(this.color),
            rangeBehavior: vscode_1.DecorationRangeBehavior.ClosedClosed
        });
        this._decoration = backgroundDecorationType;
    }
```
<img width="262" alt="aaa" src="https://user-images.githubusercontent.com/7065076/61909366-ef710100-af6c-11e9-938e-fb81e8ebacda.png">

Please add this feature to option.

**Comment by cbanack** [comment]
+1 for this.   (shungo27's change also needs to be made in src/lib/variables/variable-decoration.js)

A good way to implement this would be as a option:   Show colors as:  background, underline, or outline.

**Comment by robwierzbowski** [comment]
I would love this. Great suggestion.

**Comment by robwierzbowski** [comment]
@shungo27 FYI, This feature is available in the https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight extension.

**Comment by shungo27** [comment]
Thank you for the information. I am also trying the extension :)

**Comment by black-eye** [comment]
+1
