### ISSUE TITLE
support js languages by default

### ISSUE THREAD

**Issue by a7madgamal** [KamiKillertO/vscode-colorize#281]
to enable the plugin inside javascript I had to make some serious googling, played with the plugin settings for a while, had to read https://code.visualstudio.com/docs/languages/identifiers to finally enable it
please add `javascript`, `javascriptreact`, `typescript` and `typescriptreact` to the default languages list.
IMO, I expected this behavior when I installed this amazing plugin so why not make it easier :)

**Comment by KamiKillertO** [comment]
I will not add them for the moment because there's still some performance issues that need to be fixed before. But I've added the link https://code.visualstudio.com/docs/languages/identifiers in the description of the setting `colorize.languages`

**Comment by a7madgamal** [comment]
close enough :)
thanks!
