### ISSUE TITLE
Flutter Color 

### ISSUE THREAD

**Issue by javier-elizaga** [KamiKillertO/vscode-colorize#291]
Could it be possible to make the plugin work for a flutter project? 
Flutter is written in dart but colors are handled a little different.
Colors in flutter are hexadecimal in ARGB format. 

So 0xfffd5739 should be #fd5739, instead the plugin is displaying #fffd57

**Comment by KamiKillertO** [comment]
Colorize have support for ARGB colors, you just need to enable by updating your [`colorize.colorized_colors`](https://github.com/KamiKillertO/vscode-colorize#colorizecolorized_colors-array) setting. Replace `RGB` with ARGB

**Comment by javier-elizaga** [comment]
When I set the ARGB options the plugin stops working and I have to restart vs code. 
I have tried:

1. 
`"colorize.include": [
    "*.dart"
  ],
  "colorize.colorized_colors": [
    "ARGB",
  ]
`
2.
`"colorize.include": [
    "*.dart"
  ],
  "colorize.colorized_colors": [
    "HEXA",
    "ARGB",
  ]
`

None of them worked.
Really appreciate your help

**Comment by KamiKillertO** [comment]
Have you try removing the trailing comma after `ARGB` ?

**Comment by javier-elizaga** [comment]
Yes, but it didn't work

**Comment by KamiKillertO** [comment]
ok, I found the problem. I'll publish a new release with a fix

**Comment by javier-elizaga** [comment]
<img width="404" alt="Screenshot 2019-10-12 at 20 05 01" src="https://user-images.githubusercontent.com/4209336/66705805-b5bdc400-ed2b-11e9-92dd-83379f4089bc.png">

Hello again, 

I am still not able to make the extension work with flutter colors. In the picture, you can see that the colors are not displayed correctly. In flutter 0xfff47b20 is #f47b20

Thanks

**Comment by KamiKillertO** [comment]
Can you check again ?

**Comment by javier-elizaga** [comment]
Now, it is working, many thanks!

For people who may have this issue:
My settings.json:
`"colorize.include": [
    "*.dart"
  ],
  "colorize.colorized_colors": [
    "ARGB"
  ]`

<img width="399" alt="Screenshot 2019-10-16 at 09 27 17" src="https://user-images.githubusercontent.com/4209336/66897451-5562a700-eff7-11e9-80c7-3cd20c9d1358.png">
