### ISSUE TITLE
variables  naming with 'color's' name should not be render with bgColor; 

### ISSUE THREAD

**Issue by sjy** [KamiKillertO/vscode-colorize#30]
Perhaps the attachment describe the issue better;
![image](https://cloud.githubusercontent.com/assets/1523060/25331176/a1e00318-2914-11e7-93b1-40800be0dc25.png)

Thanks anyway.

**Comment by KamiKillertO** [comment]
🤔 yeah you're right. This one is not going to be easy to fix.
I'll work on it but the fix will not be in the next release.

**Comment by takdol** [comment]
Hi, I know this is a closed issue but is there any way for me to enable the plugin to color the custom texts for the colors? Here's a small screenshot of my Colors.js file:

<img width="252" alt="Screenshot 2020-06-03 at 9 59 44 AM" src="https://user-images.githubusercontent.com/1091549/83587630-154e3580-a582-11ea-80e1-d3c15cbed060.png">

So I would like to have the custom names (e.g. primary1) to be highlighted as the same color in this file
