### ISSUE TITLE
Dont Show alfa value(Transparancy)

### ISSUE THREAD

**Issue by abhaybhadra88** [KamiKillertO/vscode-colorize#345]
**Dont Show alfa value** in this one please update this because **Color Highlight** extention given this feature.

**Comment by IrvingArmenta** [comment]
Does not show alpha value.

example: `black` and `rgba()` : 

<img width="1071" alt="スクリーンショット 2021-01-29 11 11 08" src="https://user-images.githubusercontent.com/20631137/106222371-bd57f380-6222-11eb-8a5c-eadcb424977c.png">

**Comment by KamiKillertO** [comment]
@IrvingArmenta @abhaybhadra88 since the latest release (v0.11.0) colorize now display the color with the alpha value
