### ISSUE TITLE
If color is undefined show another color or none but no brown color

### ISSUE THREAD

**Issue by muuvmuuv** [KamiKillertO/vscode-colorize#355]
```scss
  --icon-color-light: currentColor; // ← used in SVG's to inherit text color
  --icon-color-dark: var(--icon-color-light);
```

![Bildschirmfoto 2020-01-30 um 14 25 28](https://user-images.githubusercontent.com/11534760/73453472-5df3a900-436c-11ea-9082-e9d81c73aed2.png)

**Comment by KamiKillertO** [comment]
If the color doesn't exists the extension display nothing. Maybe `--icon-color-light` is defined somewhere else
