### ISSUE TITLE
BROWSERS_COLORS work only in css files

### ISSUE THREAD

**Issue by ptkdev** [KamiKillertO/vscode-colorize#358]
Javascript file (colors.js):
```javascript
const hexColors = ['#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231'];
const textColors = ["orange", "yellow", "blue", "purple", "pink", "green", "red"];
```

Extension don't detect colors in `textColors` array.

VSCode Settings:
```json
{  ...
    "colorize.languages": ["javascript", "json", "html", "nunjucks", "css", "scss"],
    "colorize.colorized_colors": ["HEXA", "RGB", "HSL", "BROWSERS_COLORS"]
}
```

**Comment by Oliviu27** [comment]
Hi, any news on this? colors in regular js files are not detected

**Comment by viking1304** [comment]
@KamiKillertO Regex used in browser-strategy return match only with space, comma or colon before color name. With quote and double quote if fails. Adding those two as alternatives should fix this issue.

**Comment by KamiKillertO** [comment]
Sorry for the long wait. I've started working again on colorize recently and I've a lot of issues to look at ><.
I've fixed this issue and will release a new version soon 👍 .

**Comment by KamiKillertO** [comment]
Done 👍 .
