### ISSUE TITLE
Anyway to troubleshoot?

### ISSUE THREAD

**Issue by 203Null** [KamiKillertO/vscode-colorize#362]
I can't get it to work, is there's any way that I can check what went wrong? 
![image](https://user-images.githubusercontent.com/19933093/74706321-94427c80-51e4-11ea-9ff4-ba96fcd38e5b.png)
Also, can you add #AARRGGBB support?

**Comment by robquinn** [comment]
Did you find a solution for this @203Null ? I'm experiencing the same issue, can't figure it out.

**Comment by KamiKillertO** [comment]
@203Null have you try "**/UI.cpp" ?
