### ISSUE TITLE
Color-meaning words in comment should not be rendered with the color.

### ISSUE THREAD

**Issue by sjy** [KamiKillertO/vscode-colorize#37]
![wx20170517-102943](https://cloud.githubusercontent.com/assets/1523060/26135999/e2c296d2-3aeb-11e7-848e-e6fd83f25428.png)

**Comment by KamiKillertO** [comment]
I'not really sure that it's an issue.
I mean it's a valid css color but not at a good position.
But at the same time it's almost the same problem we've got here #30 🤔 🤔 🤔.

🤔 I need to think about it.

**Comment by CWolfs** [comment]
I would love to disable this too. I feel it's perfect for a settings.json option.

**Comment by KamiKillertO** [comment]
For now it's not possible
