### ISSUE TITLE
[bug] Causes vscode to get stuck in "fetching files", causes massive slowness

### ISSUE THREAD

**Issue by tcodes0** [KamiKillertO/vscode-colorize#412]
I think this was introduced recently, maybe on vscode 1.46, or recent ext update.

opening a workspace causes the ext to hang on "fetching files' (visible on bottom right) 
it also causes complete slowdown of the source control module

pretty serious bug, I've uninstalled for now. let me know how to help to get it fixed

update: aug 17: I've uninstalled for now.

**Comment by KamiKillertO** [comment]
I haven't experienced any issues with the latest versions of score and I'm working on large projects with lots of variables. Maybe the extensions is fetching too many files, have try reducing the number of files fetched by tweaking your colorize settings?

**Comment by harryxu** [comment]
I have same issue.

**Comment by montemartin** [comment]
I definitely have this, but seems to only be a issue sometimes. I think it is an iteraction with Prettier or the esbenp.prettier-vscode extension because I have lots of issues with Prettier when colorize is enabled.
