### ISSUE TITLE
add option to limit length of chars to colorize

### ISSUE THREAD

**Issue by tjx666** [KamiKillertO/vscode-colorize#437]
Like extension `cSpellCheck`, there is a configuration: `cSpell.checkLimit`, it's the  `limit in K-Bytes to be checked in a file`. 
In my project, there is a big JSON file. Every time I open it, vscode doesn't respond. @KamiKillertO

**Comment by KamiKillertO** [comment]
@tjx666 There's already many options available that can be used to prevent colorize from consuming to much memory.
The options `colorize.languages`, `colorize.include`, `colorize.exclude` can be used to target only the files that need colorizations.
The option `colorize.enable_search_variables` can be used to activate/deactivate the initial search for variables in all projects files.
The option `colorize.colorize_only_visible_beta` is close to what you're looking for, by activating this option colorizations will be generated only for the visible part of your file.
