### ISSUE TITLE
[upgrade] Needs better colors support for alfa channel !!!

### ISSUE THREAD

**Issue by maksimaliabyshev** [KamiKillertO/vscode-colorize#449]
The alpha channel is not visible under the color
![image](https://user-images.githubusercontent.com/3313882/94020892-d95b0c80-fdcc-11ea-9415-f9d97344aadd.png)

If the color has an alpha channel it is better to add a background change setting:

1. light color -> use dark alfa backgrounds
2. dark color -> use light alfa backgrounds

![image](https://user-images.githubusercontent.com/3313882/94040825-d9660700-fde2-11ea-99cf-a9c5d77c69e4.png)

colorize.colorized_alfa: boolean (default: true)
Include background for alpha colors
colorize.colorized_alfa_scale: number (default: 2)
side length of one background square svg image in pixels

**Ready background** [alfabackgrounds.svg.zip](https://github.com/KamiKillertO/vscode-colorize/files/5269680/alfabackgrounds.svg.zip)

**Comment by KamiKillertO** [comment]
Unfortunately, it's not possible to use background images for text decorations 😞

**Comment by truepatch** [comment]
> Unfortunately, it's not possible to use background images for text decorations 😞

Please look extension [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2)
settings:
"bracket-pair-colorizer-2.activeScopeCSS": [
    "borderStyle : solid",
    "borderWidth : 1px",
    "borderColor : {color}",
    **"opacity: 0.5"**
]
Similarly, you can change vscode [webview](https://code.visualstudio.com/api/extension-guides/webview),
vscode is based on electronjs and this is the web, I think there are methods or tricks to add a background with z-index

**Comment by truepatch** [comment]
@KamiKillertO I found a convenient solution - [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)
It will not take much time to implement.
If anyone needs it, he can connect this extension and get a substrate for transparent colors.
As an example of possibilities [Synthwave x Fluoromachine](https://marketplace.visualstudio.com/items?itemName=webrender.synthwave-x-fluoromachine)
