### ISSUE TITLE
hsla values not colorized in scss file 

### ISSUE THREAD

**Issue by elanalynn** [KamiKillertO/vscode-colorize#46]
Environment and versions: 
OS: OSX 10.12.5 
VSC: 1.10.2
Colorize: 0.5.1

I am trying to use hsla values in a scss file but they are not colorized. rgba and hex values in the same file are colorized as expected. 

![screen shot 2017-06-18 at 11 36 53 am](https://user-images.githubusercontent.com/7654369/27262743-84654312-541a-11e7-84e4-665a48d9213a.png)

**Comment by KamiKillertO** [comment]
Ok, the problem is that your *HUE* value is not correct. The *HUE* is a degree on the color wheel from 0 to 360. Remove the _%_ and it will work

**Comment by elanalynn** [comment]
Thank you!
