### ISSUE TITLE
Does not work in JSON files

### ISSUE THREAD

**Issue by ayako02** [KamiKillertO/vscode-colorize#470]
The extension doesn't highlight the css colours in json file

**Comment by GBrachetta** [comment]
Yes, I was hoping it would work on settings.json as well, as the extension `color highlight` became unstable and wanted to replace it.
Any plans to make it also work in JSON files?

**Comment by viking1304** [comment]
It works just fine, but you need to enable it for JSON and JSON with comments in your config.

```
    "colorize.languages": [      
        "json",
        "jsonc",
        "css",
        "sass",
        "scss",
        "less",
        "postcss",
        "sss",
        "stylus",
        "xml",
        "svg"
    ],
    "colorize.include": [
        "**/*.json",
        "**/*.css",
        "**/*.scss",
        "**/*.sass",
        "**/*.less",
        "**/*.styl"
    ]
```

**Comment by GBrachetta** [comment]
I really wished it worked, but I'm not getting it to work (at least not for my settings.json)...

**Comment by GBrachetta** [comment]
Indeed, it works! Thank you! I just miss having the decorators on the scroll bar though...

**Comment by ceyhanbekiroglu** [comment]
It works with the solution above. thanks.
