### ISSUE TITLE
Color Highlighting just broke

### ISSUE THREAD

**Issue by 275RR** [KamiKillertO/vscode-colorize#496]
Hello,
All color highlighting just broke in my CSS. The color boxes are still working.

![colorize](https://user-images.githubusercontent.com/36821077/104766820-cc25ad00-5730-11eb-92eb-3390e6ae126e.PNG)

![colorize2](https://user-images.githubusercontent.com/36821077/104767257-73a2df80-5731-11eb-90ad-a783d6f0bc21.PNG)

Great work on this extension btw. It's awesome!

**Comment by KamiKillertO** [comment]
@275RR I've just released a new version with some major changes. Check the release note to see if your config is still valid. For the color boxes, if I remember correctly the setting that control them is `color.decorations`

**Comment by 275RR** [comment]
@KamiKillertO  Thank you for the response. Please see images above.

-Color decorations are working
-Color highlighting / color backgrounds are broken for me with or without variables!

I have the default config, and I have uninstalled/reinstalled the extension. I'm on Windows 10.

**Comment by KamiKillertO** [comment]
Ok. I'll run some test on windows 10 and try to reproduce

**Comment by 275RR** [comment]
If you need any more info on my setup, or if you would like me to try anything, let me know. I would be glad to help.

**Comment by KamiKillertO** [comment]
Ok, I've managed to reproduce the issue.
Unfortunately, I cannot find a way to fix it. For some reasons, vscode on win10 does not behave as vscode on linux. Normally, colorize get all extensions installed on vscode and match them with the list of languages listed in the setting `colorize.languages` to get a list of file extensions to search variables in. But, on windows 10 the built-in extensions are not exposed 😒. As a result CSS ans SASS variables are not extracted.

If you want to have the variables extracted by default for css you need to add `"**/*.css"` in the `colorize.include` setting.

I've also released a new version who search for variables in `*.css,*.scss,*.sass,*.less` files by default. I'm planning on improving this part in future releases to help identify which files are red during variables extraction.

**Comment by 275RR** [comment]
@KamiKillertO Thanks, this is the best extension for CSS on vscode.

1. I checked another win10 machine and everything is working now with the hotfix including CSS variables.
2. For my machine, I found that the Tabnine AI extension is conflicting with this Colorize update. If I disable Tabnine, Colorize works.

Should I close this issue or leave this open until future improvements for variable extraction?

**Comment by KamiKillertO** [comment]
No that's ok you can keep this issue open. I'll run some tests with tabnine AI to found what the problem is

**Comment by KamiKillertO** [comment]
I've fixed the issue with Tabnine 👍

**Comment by 275RR** [comment]
Re-enabled Tabnine. No issues!
