### ISSUE TITLE
Hide default color preview squares?

### ISSUE THREAD

**Issue by nmsmith22389** [KamiKillertO/vscode-colorize#5]
On your extension screenshot you don't have any of the normal color preview squares and I've been dying to get rid of them. How did you do that? It sucks having both and not having an option to get rid of the normal ones.

**Comment by KamiKillertO** [comment]
There's no squares because I've recorded the gif ussing a sass file ^^.
There's no way to disable the preview yet.
There an open PR [here](https://github.com/Microsoft/vscode/issues/10943)

**Comment by nmsmith22389** [comment]
thanks!

**Comment by KamiKillertO** [comment]
Hey it seems that you can disable colors preview in vscode 1.10. https://code.visualstudio.com/updates/v1_10#_css

**Comment by nmsmith22389** [comment]
## FINALLY!! 🎊

Thanks for the info!

**Comment by ryanjbonnell** [comment]
For others who might come across this, as of VS Code v1.16 (August 2017) the built-in [CSS/JSON color preview setting](https://code.visualstudio.com/updates/v1_16#_cssjson-color-preview) is now `editor.colorDecorators`:

> _We moved the inline color preview rendering from the CSS/JSON extensions to the VS Code core and in the process deprecated four configuration settings: `css.colorDecorators.enable`, `sass.colorDecorators.enable`, `scss.colorDecorators.enable` and `json.colorDecorators.enable`._
>
> _There is a new general setting `editor.colorDecorators` to control if the inline color box should be rendered._

https://github.com/microsoft/vscode/issues/62325
