### ISSUE TITLE
Hex alpha support

### ISSUE THREAD

**Issue by danblink** [KamiKillertO/vscode-colorize#50]
Hi, I love this extension but was hoping support for hexadecimal colors with alpha could be supported. While it's not a widely used color notation, VS code does allow them for workbench color customizations in settings and it would be useful for theming. I was going to fork and make a pull request, but it seemed like overkill since it is a one line change. All that needs to be done is change line 4 in `./src/lib/extractors/hexa-extractor.ts` from `export const REGEXP = /(#[\da-f]{3}|#[\da-f]{6})(?:$|"|'|,| |;|\)|\r|\n)/gi;` to `export const REGEXP = /(#[\da-f]{3}|#[\da-f]{6}|#[\da-f]{8})(?:$|"|'|,| |;|\)|\r|\n)/gi;`. This will make the regex accept the extra 2 characters, but no other change is needed since the conversion to RGB only accepts the first 6 characters and will discard the extra 2. The RGBA extractor seems to discard the alpha channel so this behavior seems appropriate. Let me know if this could be added, thanks!

**Comment by KamiKillertO** [comment]
Thanks a lot ❤️ .

I will add support for 4 and 8 digit hexa colors in the next release (should be release soon :crossed_fingers: ).
So colors like `#ffff`and `#ffffffff`will be colorized but the alpha value will be drop for the decoration (like with rgba) as there's no way (yet) to generate decoration with a gradient background.

**Comment by danblink** [comment]
Great to hear! Thank you so much, keep up the awesome work 😊

**Comment by KamiKillertO** [comment]
I've release a new version `0.6.0`with the bugFix ^^
