### ISSUE TITLE
Status bar item has bad contrast

### ISSUE THREAD

**Issue by miguelsolorio** [KamiKillertO/vscode-colorize#503]
![image](https://user-images.githubusercontent.com/35271042/105546513-554d5e80-5cb2-11eb-931d-58fd0bdee93a.png)

I think this is recently new, but not a fan of this item and it also has bad contrast.

**Comment by KamiKillertO** [comment]
Indeed the color contrast is not ideal 🤔. I've taken inspiration from the vscode-eslint extension but it seems there's room for improvements.
As for the the item in itself his purpose is to help users know if the extension is active for the current file. In future releases I will update this item and the possibility to enable/disable colorize by clicking on it.

**Comment by misolori** [comment]
Ah, so that is getting an update in the next VS Code version that allows you to use a background color instead, see https://github.com/microsoft/vscode/issues/110214

Would love for a setting to hide this too 🙏  big fan of the extension btw, thanks!

**Comment by KamiKillertO** [comment]
Thanks for link 👌
