### ISSUE TITLE
Colorizing strings

### ISSUE THREAD

**Issue by Mofunkles** [KamiKillertO/vscode-colorize#504]
I don't know if this is due to a recent update or if I just haven't ever typed a colour in a string before now, but in Javascript, if I'm typing words that are the browser colours like 'blue' 'yellow' etc it's being highlighted.

The extension seems to be working fine in other filetypes like if I'm typing text containing colours inside of .html.  Not tried any other languages than JS.

The only ways I see to disable this for now are to either disable the browser colour highlighting, or to disable colorize for .js files for the time being!

**Comment by djmisterjon** [comment]
be sure add all language 
```json
  "colorize.include": [
    ".tsx",
    ".jsx",
    ".ts",
    ".js"
  ],
  "colorize.languages": [
    "css",
    "sass",
    "scss",
    "less",
    "postcss",
    "sss",
    "stylus",
    "xml",
    "svg",
    "html",
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
  ],
```
