### ISSUE TITLE
Colorize Disabled?

### ISSUE THREAD

**Issue by mikeerickson** [KamiKillertO/vscode-colorize#508]
Just recently, it seems colorize is not loading.  I have done the following

- reinstalled extension
- restarted VSCode
- tested with both release (and insiders)

![image](https://user-images.githubusercontent.com/183153/106403462-b4625000-63e3-11eb-835a-b30eaf80bd91.png)

Any suggestions?

**Comment by gregkonush** [comment]
experiencing the same issuer over here, tried the step above as well that didn't help.

**Comment by yy523697597** [comment]
I have the same error.and vscode show the plugin take too much time to initialize.

**Comment by KamiKillertO** [comment]
@mikeerickson, @gregkonush, @yy523697597 I need some information in order to help you.
Of what kind of files do you have the problem? And what OS are you on?
Also, a small precision, the message displayed only means that colorize is no activated for the current file, it doesn't mean that colorize is not activated at all.

**Comment by yy523697597** [comment]
@KamiKillertO I'm using macOS 11.2 based on arm, m1 chipset.  And the vscode is 1.53 insider version.

**Comment by KamiKillertO** [comment]
Ok so for you it's another problem. Can you share your vscode config (only the colorize part ^^)

**Comment by mikeerickson** [comment]
> @mikeerickson, @gregkonush, @yy523697597 I need some information in order to help you.
> Of what kind of files do you have the problem? And what OS are you on?

I am using 

- VueJS Single File Components
- SCSS
- CSS

- macOS Mohave

**Comment by mikeerickson** [comment]
@KamiKillertO I am a tad confused about this issue actually.   While the error is indeed displayed in the status bar, it seems the actual functionality of this plugin is still working (see screenshot).

![image](https://user-images.githubusercontent.com/183153/106974849-429f4480-670a-11eb-8dc8-629796136ccf.png)

Unless VSCode his this same functionality intheritely. one would believe it does work?

**Comment by elastiboy** [comment]
I just installed Colorize and facing the same issue.

**Comment by Teaguey** [comment]
Having the same issue here on **Mac OS Big Sur 11.3**. Have tried the basics, was working on my windows PC which already had Colorize installed. Hasn't worked since I got my mac 2 weeks ago. I've been testing it on a js file that worked fine on my PC. Let me know if there's any info you need.

**Comment by usernein** [comment]
Same happening for me! I just installed it on a studio code server running on a raspberry 4B. I'm using macOS Monterey 12.3.1

**Comment by albjeremias** [comment]
> @mikeerickson, @gregkonush, @yy523697597 I need some information in order to help you. Of what kind of files do you have the problem? And what OS are you on? Also, a small precision, the message displayed only means that colorize is no activated for the current file, it doesn't mean that colorize is not activated at all.

yeah for me it doesn't get active in typescript files

**Comment by sommerper** [comment]
It's showing red for me when I'm on the VSCode settings page. I think it just means that the current file does not contain anything to colorize.

It should probably just be changed to the default color to avoid confusion and make it look like something isn't working.
