### ISSUE TITLE
html中插入css  颜色  在colorize.languages如何添加

### ISSUE THREAD

**Issue by this-Me** [KamiKillertO/vscode-colorize#54]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style type="text/css">
     div{
       color: seashell;

     }
  </style>
</head>
<body>
  <div>1
   <p>Hellow world</p>
  </div>
</body>
</html>

**Comment by you06** [comment]
这样做，还有作者是法国人最好用英文提问吧
```json
{
  "colorize.languages": [
    "html"
  ]
}
```
