### ISSUE TITLE
False positive when typing 1920x1080

### ISSUE THREAD

**Issue by luisrudge** [KamiKillertO/vscode-colorize#574]
Hi, there. When I have a string with the FULL HD resolution, colorize think that's a color 😬 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/941075/115943662-a292c500-a487-11eb-86ef-13a54b4a3c45.png">

**Comment by IIAydedeII** [comment]
![image](https://user-images.githubusercontent.com/75357323/128147869-c0516710-0a8d-4aa3-8867-d42cf4e61372.png)
I'm having the same issue here. It would be nice to see it fixed.

**Comment by tjx666** [comment]
fixed in my version: https://marketplace.visualstudio.com/items?itemName=YuTengjing.vscode-colorize-plus
