### ISSUE TITLE
Visual updating of custom properties requires reload

### ISSUE THREAD

**Issue by evanwarner** [KamiKillertO/vscode-colorize#59]
So the new support of variables and custom properties seems to be working in general. But I did notice that instances of custom properties don't update until I reload VSC.

If I type out
```css
:root {
  --myVar: #FFF;
}

p {
  color: var(--myVar);
}
```
the `#FFF` will be colorized immediately but the `var(--myVar)` will not be until I reopen the project or reload the window. After that though, new references to `var(--myVar)` get highlighted immediately.

Also, if I change the value of `--myVar` or add a localized version inside the `p` declaration, references to it are not updated until a reopen/reload.

I can record a screencast if that will help.

**Comment by KamiKillertO** [comment]
No need to record screencast.
Updates are not supported yet 😿, it will require a major code refacto 😞.
