### ISSUE TITLE
[Feature Request] Command to toggle colorizer based on file 

### ISSUE THREAD

**Issue by laggardkernel** [KamiKillertO/vscode-colorize#596]
This colorizer plugin is very powerful with so many options. The `"colorize.languages"` option is not enough to meet my need. Sometimes I wanna enable it for the current file, but I don't find any commands provided. I suggest we add a command to toggle colorize manually.

- Switch colorization on/off with this command
- The colorization state should be memorized, which means when switching back to current tab (file), the colorization state is not changed.

**Comment by KamiKillertO** [comment]
@laggardkernel It's planned 😅 . In a future release, I'll improve the bottom icon and add the possibility to enable/disable directly from it.
Yeah the `colorize.languages` option is not enough, this is why there are the options `colorize.include` and `colorize.exclude` that let your define file paths or globs pattern to control whenever colorize is activated or not.
