### ISSUE TITLE
Background fills new lines created in colored strings in Sass

### ISSUE THREAD

**Issue by YuziRussianHax** [KamiKillertO/vscode-colorize#6]
Place mouse on colored string
![image](https://cloud.githubusercontent.com/assets/14042959/22515468/3ca6463c-e8ab-11e6-8940-c1f3e9336928.png)

Start new line
![image](https://cloud.githubusercontent.com/assets/14042959/22515511/5f8cf8a8-e8ab-11e6-9720-2fbf5f4f2468.png)

Same happens even If I delete whole number.
This happens untill I re-open window with styles (which reloads plugin initialization).

System: Ubuntu 10.16
Editor: VSCode 1.8.1
Using UTF-8, LF for new lines.

**Comment by KamiKillertO** [comment]
Indeed.
This should be fix in the next version.

**Comment by you06** [comment]
This happens while write after color code instead after semicolon, I have the same problem while using stylus.

**Comment by KamiKillertO** [comment]
v0.3.0 is out, all background issues should be fix now ^^

**Comment by YuziRussianHax** [comment]
@KamiKillertO awesome job, thank you <3
