### ISSUE TITLE
Color background not displaying since 1.14.2 update

### ISSUE THREAD

**Issue by ekfuhrmann** [KamiKillertO/vscode-colorize#66]
I really like your extension; however, it seems that after today's VScode update it no longer is working. I don't think I did anything that could have effected it other than that update but let me know if there is anything further I could provide you to assist.

Thanks.

**Comment by KamiKillertO** [comment]
🤔 everything works fine on my machine 🤔

Did you set `colorize.activate_variables_support_beta` at `true` ?

**Comment by ekfuhrmann** [comment]
Whoops, I did have that set to `true` but it seems like I had to restart VScode for it to propagate through. My mistake for trying that prior to creating the issue. Thanks for helping get it sorted!

**Comment by KamiKillertO** [comment]
It's ok. Variables support is still in beta 😄.
🤔 is it possible to have the logs from your vscode ? It might be usefull ^^

**Comment by ekfuhrmann** [comment]
How would I go about getting those logs from last Friday?

**Comment by KamiKillertO** [comment]
Reopen your project/folder.
Set `colorize.activate_variables_support_beta` at `true` again.
Open `Help` menu and click `Toogle Developer Tools`.

<img width="420" alt="screen shot 2017-07-25 at 10 21 41" src="https://user-images.githubusercontent.com/9579729/28562667-8065de72-7123-11e7-9971-86d8314f196f.png">

And reload vscode : `⌘⇧P` => `reload window`

After that you will a chrome devtool opened with all your error logs inside ^^

**Comment by ekfuhrmann** [comment]
Not sure how much value this will be to you, but this is what the console is saying after refresh...

![image](https://user-images.githubusercontent.com/8878152/28573721-85cd5db8-7119-11e7-8a34-6fd4016c8324.png)

I've had that variable set to true without issue since last Friday, but if I do see it messing up again I'll be sure to take note of the log for you.

**Comment by KamiKillertO** [comment]
Thanks a lot 😄
