### ISSUE TITLE
Add colorize for rgb color

### ISSUE THREAD

**Issue by you06** [KamiKillertO/vscode-colorize#7]
hex color code will be colorized but the rgb color code will not.

<img width="457" alt="2017-02-02 23 56 18" src="https://cloud.githubusercontent.com/assets/9587680/22556848/854eea4e-e9a3-11e6-9a30-63267f44d679.png">

**Comment by KamiKillertO** [comment]
I've plan to add support for rgb colors in the next version.
I've also plan to add a partial support for rgba colors (the rgb base color will be used for the background)

**Comment by KamiKillertO** [comment]
v0.3.0 is out with rgb support.
If you encounter any error feel free to create issue
