### ISSUE TITLE
Does it work on Vue files?

### ISSUE THREAD

**Issue by AhmedBoustani** [KamiKillertO/vscode-colorize#72]
I use Sass to style my Vue pages but Colorize doesn't seem to work on .vue files even after I added it to the languages. Am I doing something wrong or it just doesn't work on them?

**Comment by KamiKillertO** [comment]
🤔 do you use an extension like this [one](https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue).

**Comment by AhmedBoustani** [comment]
Yes, I'm using that exact one, in addition to [this](https://marketplace.visualstudio.com/items?itemName=mubaidr.vuejs-extension-pack)

**Comment by KamiKillertO** [comment]
It works on my machine 🤔 
<img width="302" alt="screen shot 2017-08-28 at 16 23 29" src="https://user-images.githubusercontent.com/9579729/29777725-44dea802-8c0d-11e7-875a-ef1d38e03840.png">

**Comment by KamiKillertO** [comment]
Maybe there's something on your file

**Comment by AhmedBoustani** [comment]
Yeah looks like it. Thanks! And good job! It works really well everywhere else and it's just what I want!! I'll just try to make it work on my vue files.

**Comment by KamiKillertO** [comment]
Can you share your file content?

**Comment by AhmedBoustani** [comment]
Actually I can't, it's a whole project for work. I used to have a colorizer but I hated the fact that the background stays colored when I click on the hex.
It worked on a new file like the one you just showed me, but for some reason it only happened once and I can't seem to be able to recreate it. I'll let you know if I figure something out. It might be a problem with my vscode settings
