### ISSUE TITLE
Does not include highlights to first line of code... examples attached below

### ISSUE THREAD

**Issue by BattleKing28** [KamiKillertO/vscode-colorize#720]
![2021-10-05](https://user-images.githubusercontent.com/56110324/136028706-e74fa514-54ed-468a-b1f5-eab4aff19bb6.png)
![2021-10-05 (2)](https://user-images.githubusercontent.com/56110324/136028712-919e6c65-dcf4-4946-9c51-5328985220b0.png)
![2021-10-05 (3)](https://user-images.githubusercontent.com/56110324/136028716-c48905ec-8d95-4249-ab62-5b671e949bcd.png)

**Comment by tjx666** [comment]
I can't reproduce with default config, can you reproduce it with default config?
