### ISSUE TITLE
colorize: 0 variables detected? 

### ISSUE THREAD

**Issue by alexzhaohong** [KamiKillertO/vscode-colorize#737]
How do I get variable `colors.color` to render?

colorize.enable_search_variables is true.

<img width="574" alt="Screen Shot 2021-11-10 at 3 42 03 PM" src="https://user-images.githubusercontent.com/12620082/141190932-52018afe-5f6f-4763-b84a-c98ff9b8bf47.png">

<img width="525" alt="Screen Shot 2021-11-10 at 3 49 00 PM" src="https://user-images.githubusercontent.com/12620082/141191104-f11606e1-b84d-4dbd-aad7-66d96b1ce838.png">

```

    "colorize.languages": [
        "css",
        "scss",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
      ],
    "colorize.hide_current_line_decorations": false,
    "colorize.colorized_variables": [
        "CSS",
    ],
}

```

**Comment by tjx666** [comment]
This extension seems to working using text match, but you want using it with runtime variable value...

**Comment by alexzhaohong** [comment]
> This extension seems to working using text match, but you want using it with runtime variable value...

The extension does offer variable matching functionality with `colorize.colorized_variables`

**Comment by tjx666** [comment]
That for css variable or othe css pre-precess language, not for other languages which need to run. Css can be analyzed using lsp or ast parser, but ts is a script language, for a variable, that value should be know only after run it. For a browser ts code, how you know the value of it?

**Comment by KamiKillertO** [comment]
> The extension does offer variable matching functionality with colorize.colorized_variables

It only works with (simple) SASS, LESS, STYLUS, and CSS variables.
It does not support JS variables
