### ISSUE TITLE
Variables Support + Typo in Options example

### ISSUE THREAD

**Issue by TonySpegel** [KamiKillertO/vscode-colorize#76]
I have no idea how to turn on variables support.
The GIF provided [here](https://raw.githubusercontent.com/kamikillerto/vscode-colorize/master/assets/demo_variables.gif) doesn't help much either.
Imitating the GIF doesn't do anything.

I've added the short option snippet to my user settings and restarted VS Code.

There's also a typo in your options example [here](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize#overview): right now it's:   
`"colorire.hide_current_line_decorations": true`
but should be obviously:   
`"colorize.hide_current_line_decorations": true`   
so colorize not colorire ;)

**Comment by KamiKillertO** [comment]
There's a typo indeed 😖. In order to activate variables support you need to set `colorize.activate_variables_support_beta` to `true` as mentioned un the README 😉

**Comment by TonySpegel** [comment]
Havn't seen that as the GIF implies you have to type something in ordner to activate it - doesn't seem that clear to me. 

Still doesn't do anything and also shouldn't these small inline color picker squares be hidden by 
"colorize.hide_current_line_decorations" or am I wrong?

**Comment by KamiKillertO** [comment]
There's `How to enable variables support` just below the gif 😉.
For the square preview you can have a look [here](https://github.com/KamiKillertO/vscode-colorize/issues/5).

🤔 So it's still not working 🤔🤔. Did you reload? What kind of files are you using?

**Comment by TonySpegel** [comment]
`"editor.colorDecorators": false` disabled the square preview.

Yeah I've reloaded VS Code. Im using scss-Files like this:
`$active-color    : #333;
$text-color      : $active-color;`
so the second variables should ne highlighted in #333

Also should imported variables work?

**Comment by KamiKillertO** [comment]
🤔 huuum. At the right bottom of vscode you should see messages, `Found xx files`, `Found xx variables`. Did you see them, or did you only see `Found xx files`?

**Comment by KamiKillertO** [comment]
What do mean by imported variables? Variables from `npm` packages?

**Comment by TonySpegel** [comment]
I can see `Found 6 Variables`, there's no `Found xx Files`

Let's say I have one file where I define my variables, that would be _variables.scss and another one like _buttons.scss, inside _buttons.scss I'd do sth. like `@import '_variables';` also I'd to reference variables from my variables file inside of buttons - that would be an import. In this case, every variable mentioned in buttons should have colors too.

Looks sth. like this: https://i.imgur.com/L54ACHK.png

**Comment by KamiKillertO** [comment]
Ok I see, I do not support `@import`. But the variables should be colorize even without `@import`.
Because my extension fetch all project files to find variables and them colorize variables.

**Comment by KamiKillertO** [comment]
🤔 huuum I think I known why it's not working. I think it's because there's spaces beetween the variables n'aime and `:`. Can you truc without spaces?

**Comment by TonySpegel** [comment]
I'll try that this evening :) - although I like to to order my code this way. Anyway, imported variables are more important for me :)

**Comment by KamiKillertO** [comment]
I made few tests and the problem comes from the spaces between the variable name and the `:`. I will fix it soon

**Comment by TonySpegel** [comment]
Hey sorry for not reporting back, totally forgot about it :( - thanks for fixing it

**Comment by KamiKillertO** [comment]
v0.6.8 is out with a fix for your issue 😄
