### ISSUE TITLE
Colorize on file extension .html

### ISSUE THREAD

**Issue by alksndr0s** [KamiKillertO/vscode-colorize#78]
I've tried to make it work with my styles inside .html files but I couldn't.

I tried with:
"colorize.languages": [
     "html",
     ...
],
and also with:
"colorize.files_extensions": [".html"],

Is this a known issue, or perhaps I'm doing something wrong?

Many thanks in advance :)

**Comment by KamiKillertO** [comment]
🤔 did you reload vscode after? Have you enable the variables support ?

**Comment by alksndr0s** [comment]
I did reload several times, and I did't enabled the variables support yet.
Is suddenly solved now, it works perfectly. It seems that my machine malfunctioned causing this issue.

All good here, thanks for the support and congrats for the good work

**Comment by KamiKillertO** [comment]
Thanks 😄
