### ISSUE TITLE
Long CSS files

### ISSUE THREAD

**Issue by procmail** [KamiKillertO/vscode-colorize#8]
Hi,

When switching between tabs that contain very long CSS files, Visual Studio Code seems to become unresponsive., to the extent where a popup window appears and asks if you want to continue waiting.

**Comment by KamiKillertO** [comment]
Yeah I know, I've to improve the perf.
Can you give the number of line of your files?

**Comment by KamiKillertO** [comment]
Problem solved ✔️.
The generation of backgrounds take less than 1s for a file with 17000 lines ^^.
I will release a new version with the correction soon.

**Comment by procmail** [comment]
17000 lines is more than what I have :)

Will test the new version when it's out.

Thanks for the good work.

**Comment by KamiKillertO** [comment]
I've just released the v0.3.1
