### ISSUE TITLE
Tailwindcss support?

### ISSUE THREAD

**Issue by Jonatthu** [KamiKillertO/vscode-colorize#871]
Is there a roadmap to support tailwind?

**Comment by johtso** [comment]
Possibly something that tailwind should incorporate into intellisense? https://github.com/tailwindlabs/tailwindcss-intellisense/issues/731

**Comment by devbytemehedi** [comment]
I have been using this extension till i learned tailwind now it's hard to go back to vanilla css.

**Comment by KamiKillertO** [comment]
Will add it once I've fix the performances issue and change how colors are extractect

**Comment by thecodermehedi** [comment]
> Will add it once I've fix the performances issue and change how colors are extractect

I installed the extension but you didn't specify how do i need to enable this , by default it doesn't do anything

**Comment by KamiKillertO** [comment]
> I installed the extension but you didn't specify how do i need to enable this , by default it doesn't do anything

What do you mean?
Tailwind support is still not a thing

**Comment by thecodermehedi** [comment]
> > I installed the extension but you didn't specify how do i need to enable this , by default it doesn't do anything
> 
> What do you mean?
> Tailwind support is still not a thing

I thought you closed this issue as completed ?

**Comment by KamiKillertO** [comment]
I've closed as I'm not planning on adding support for tailwind for not.
It's already difficult to support all type of colors and CSS preprocessor. To support tailwind I'll need to either connect with the Tailwind extension or rewrite a part of the Tailwind extension 😬

**Comment by thecodermehedi** [comment]
> I've closed as I'm not planning on adding support for tailwind for not. It's already difficult to support all type of colors and CSS preprocessor. To support tailwind I'll need to either connect with the Tailwind extension or rewrite a part of the Tailwind extension 😬

Okay, Thank you for at least trying.
