### ISSUE TITLE
$ vars don't show the colors

### ISSUE THREAD

**Issue by natibs** [KamiKillertO/vscode-colorize#876]
![image](https://user-images.githubusercontent.com/10099701/204128823-3cd8c175-0fbc-494c-bfd9-0baa40a8ef6a.png)

**Comment by KamiKillertO** [comment]
Support for sass variable is available, just activate it in the setting https://github.com/KamiKillertO/vscode-colorize?tab=readme-ov-file#colorizecolorized_variables
