### ISSUE TITLE
Don't manage several projects with same variable naming

### ISSUE THREAD

**Issue by Nath-sticky** [KamiKillertO/vscode-colorize#88]
Hi there!

I have a very annoying issue. I am working on 3 projects inside 1 big project. So my sass folder is something like that:

/sass 
 - /first-project/
   - _variables.scss
   - _file.scss
   - _.........scss
   - main.scss
 - /second-project/
   - _variables.scss
   - _file.scss
   - _.........scss
   - main.scss
 - /third-project/
   - _variables.scss
   - _file.scss
   - _.........scss
   - main.scss

And on my first and second project, my variables are not in the good color :( It's take only color of my third project... Obviously, I can't rename my variables :D Do you have a solution for that?

**Comment by KamiKillertO** [comment]
🤔 currently I use the latest declaration to generate the decoration.
I will update this behavior to use the closest declaration 😄

**Comment by Nath-sticky** [comment]
Perfect!

**Comment by KamiKillertO** [comment]
I've just release a new version that should fix your issue ^^. Let me know if you still have issues
