### ISSUE TITLE
Performance Issue - High Profile MS

### ISSUE THREAD

**Issue by violetbee** [KamiKillertO/vscode-colorize#894]
You might want to check attached txt file

![image](https://user-images.githubusercontent.com/61601796/235905624-490fac83-e205-4470-b9a7-5b96578a808d.png)

[kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt](https://github.com/KamiKillertO/vscode-colorize/files/11382025/kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt)

**Comment by bombillazo** [comment]
Ensure you use the `"colorize.exclude"` in the VS  code settings option to ignore files inside your repo. If not, it'll scan **EVERYTHING** like build files, dist folders, etc.
