### ISSUE TITLE
Feature request: OKLAB support

### ISSUE THREAD

**Issue by sergio-ezquerro-ochagavia** [KamiKillertO/vscode-colorize#898]
As stated in the title, I request support for oklab colors. 
This change could make it (_much_) easier to select color palletes in the future

**Comment by Jinan-Dangor** [comment]
I'd like to second this motion. Love the oklab colour space and use oklch for all my colour schemes.
Right now the extension Color Highlight supports (some) oklab syntax, but doesn't support css variables (one of colorize's many lifesaving features). So I use it to view what colours I'm assigning my variables to but can't see what they are when I use them.

**Comment by KamiKillertO** [comment]
It should be rather simple to add support for simple oklab colors

```
oklab(40.1% 0.1143 0.045);
oklab(59.69% 0.1007 0.1191);
oklab(59.69% 0.1007 0.1191 / 0.5);
```
I will work on it for the new version

**Comment by Jinan-Dangor** [comment]
Glad to hear it! `oklab()` and `oklch()` are very useful, and I love using this extension, so glad to hear they'll be added!

**Comment by KamiKillertO** [comment]
I've just release a new version with support for both

**Comment by sergio-ezquerro-ochagavia** [comment]
Okay it works! (Kinda hahah) 

![image](https://github.com/user-attachments/assets/91cec683-7dd4-4fdb-925b-3bc916b76da7)
