### ISSUE TITLE
Not support in .tsx file

### ISSUE THREAD

**Issue by chenweiyi** [KamiKillertO/vscode-colorize#904]
Problem:

It not works in .tsx file, but when i modify file to .ts file, it works.

my vscode settings is below: 

```js
"colorize.languages": [
    "javascript",
    "ts",
    "tsx",
    "typescript",
    "vue",
    "css",
    "sass",
    "scss",
    "less",
    "postcss",
    "sss",
    "stylus",
    "xml",
    "svg"
  ],
```

May I ask, how to set the language so that it takes effect in the .tsx file?

**Comment by SitrucL** [comment]
what was the solution for this?

**Comment by chenweiyi** [comment]
add `typescriptreact` in `colorize.languages`
