### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by th3w1zard1** [KamiKillertO/vscode-colorize#923]
[kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17690533/kamikillerto.vscode-colorize-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-colorize`
- Extension Version: `0.11.1`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.95.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by th3w1zard1** [comment]
edit: my bad about the duplicate issue, vs code just kind of did its own thing here.

While I feel this problem still exists and is unresolved, unrelated to my environment, please feel free to close if it indeed is a duplicate :)

**Comment by KamiKillertO** [comment]
This should have been fixed now.
