### ISSUE TITLE
Incorrect conversion of some HSL parameters

### ISSUE THREAD

**Issue by maltenuhn** [KamiKillertO/vscode-colorize#94]
Pure grayscale colour values are recognised (and displayed) as black. 
`hsl(0, 0%, 20%);
  hsl(0, 0%, 40%);
`
As soon as one of the params h and s is > 0, it functions correctly.

**Comment by KamiKillertO** [comment]
Everything seems fine.
 
![screen shot 2017-11-16 at 10 13 41](https://user-images.githubusercontent.com/9579729/32883250-2317e312-cab7-11e7-8bc5-94152ec2fb56.png)

**Comment by KamiKillertO** [comment]
Can you add a screenshot of your problem?

**Comment by maltenuhn** [comment]
I think it was a problem with an older version, disappeared on upgrade. Closing this, sorry for the trouble!

**Comment by KamiKillertO** [comment]
No problem 👍
