### ISSUE TITLE
Activate variables

### ISSUE THREAD

**Issue by sametsafak** [KamiKillertO/vscode-colorize#97]
I guess colorize.activate_variables_support_beta is written for show the colors of less/sass variables.

**When I activate this feature;**
-I can see the variables' colors and other colors perfectly on my Mac (High Sierra),
-But on Windows 10 I can't see neither variables' colors nor normal colors (provided by colorize, vscode's colors are ok) . Do you know this problem or can I help you to detect this problem?

**Comment by KamiKillertO** [comment]
First the usual question. Did you restart vscode after settings the setting to true?

**Comment by sametsafak** [comment]
Yes I did again and again. Even I tried fresh install.

**Comment by sametsafak** [comment]
I tried it in another windows 10 pc, still same.

**Comment by KamiKillertO** [comment]
Ok I've found the problem, I'll fix it soon and release a new version. Thanks for the feedback 👍
